spring:
  data:
    mongodb:
#      uri: mongodb+srv://gaurab:gaurab@cluster0.qoxoi6d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
mail:
  host: smtp.gmail.com
  port: 587
  username: gaurabchand655@gmail.com
  password: Gaurab
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true



server:
  port: 8082
  servlet:
    context-path: /journal
